// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package gen_readwise_sqlc

import (
	"time"
)

type Book struct {
	ID              int64
	Title           string
	Author          string
	Category        string
	Source          string
	NumHighlights   int64
	LastHighlightAt time.Time
	Updated         time.Time
	CoverImageUrl   string
	HighlightsUrl   string
	SourceUrl       string
}

type Highlight struct {
	ID            int64
	Text          string
	Note          string
	Location      int64
	LocationType  string
	HighlightedAt time.Time
	BookID        int64
	Url           string
	Color         string
	Updated       time.Time
	Tags          string
}
